name: Build Container

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  build_container:
    name: Build Docker Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Docker Tag
        id: docker-tag
        run: |
          echo "DOCKERTAG=${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}-$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Docker container build
        id: build_container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/gitblamecarrot/webring:${{steps.docker-tag.outputs.DOCKERTAG}}